BENCHMARK: train
route_rel: leaderboard/data/training/routes/s1/Town01_Scenario1.xml
routes: ${eval.route_rel}
scenarios_rel: leaderboard/data/training/scenarios/s1/Town01_Scenario1.json
scenarios: ${eval.scenarios_rel}